on: [push]
jobs:
  container-job:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Python installation
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Dependencies installation
      run: |
        python3 -m pip install --upgrade pip
        pip install -r tests/requirements.txt
    - name: Make .env file
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        envkey_POSTGRES_INNER_PORT: ${{ secrets.POSTGRES_INNER_PORT }}
        envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        envkey_POSTGRES_INNER_HOST: ${{ secrets.POSTGRES_INNER_HOST }}
    - name: Start docker container
      run: docker compose up -d --build
    - name: Test api
      run: python3 manage.py test tests
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Dependencies installation
      run: |
        python -m pip install --upgrade pip
        pip install flake8==7.1.1
    - name: Flake8
      run: flake8